# Use YAML for configuration since it allows comments like this
site_name: Nn
description: |
  Do you love Pelican? Can't enough of that Jekyll? Then Nn is probably not
  for you.
author: Leonardo Uieda
language: en
repository: leouieda/nene
twitter: leouieda
url: https://nene.leouieda.com
favicon: images/favicon.png
logo: images/nene-logo.svg
thumbnail: images/thumbnail/default.png
menu:
  - [Home, index]
  - [Rock Physics, rp]
  # - [Attributes, attributes]
  - [Simulation, wavefield]
  # - [Inversion, inversion]
ignore:
  - README.md
  - config-alternative.json
  - "*.py"
